# -*- coding: utf-8 -*-
"""
Minimal photonic time-delay reservoir for spike-train classification.

Input: spike trains generated by lidar_to_spike_demo (compressed LiDAR echoes).
Three scene classes:
  0 - single target
  1 - two targets
  2 - three targets

The reservoir is a simple delay-line network: each spike is replicated through
a bank of delayed taps, passed through a nonlinearity (emulating a QD laser
neuron or MRR weight node), and a linear readout is trained to classify scenes.
"""
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "results")


def generate_spike_scene(t, class_id, rng, noise=0.05):
    """Generate a spike train for one of three scene classes."""
    spikes = np.zeros_like(t)
    if class_id == 0:
        delays = [1.0e-12]
        amps = [1.0]
    elif class_id == 1:
        delays = [0.8e-12, 2.2e-12]
        amps = [1.0, 0.7]
    else:
        delays = [0.6e-12, 1.6e-12, 3.0e-12]
        amps = [1.0, 0.65, 0.4]

    for d, a in zip(delays, amps):
        d += rng.normal(0, noise * d)      # small timing jitter
        a *= rng.uniform(0.85, 1.15)       # amplitude fluctuation
        spikes += a * np.exp(-((t - d) / (0.12e-12))**2)
    return spikes


def reservoir_states(spikes, delays, weights, dt, nonlin=np.tanh):
    """
    Time-delay reservoir: for each time step, state = tanh(sum of delayed
    spike trains weighted by random weights).
    """
    N, T = len(delays), len(spikes)
    states = np.zeros((T, N))
    for i, d in enumerate(delays):
        shift = int(round(d / dt))
        delayed = np.zeros_like(spikes)
        if shift >= 0:
            delayed[shift:] = spikes[:-shift] if shift > 0 else spikes
        else:
            delayed[:shift] = spikes[-shift:]
        states[:, i] = nonlin(weights[i] * delayed)
    return states


def main():
    # load the time axis from previous demo
    d = np.load(os.path.join(OUT, "lidar_to_spike_demo.npz"))
    t = d["t"]
    dt = t[1] - t[0]

    # generate dataset
    rng = np.random.default_rng(42)
    n_samples = 150
    X, y = [], []
    for _ in range(n_samples):
        cls = rng.integers(0, 3)
        spikes = generate_spike_scene(t, cls, rng)
        X.append(spikes)
        y.append(cls)
    X = np.array(X)
    y = np.array(y)

    # reservoir parameters
    n_delays = 20
    delay_values = np.linspace(0.2e-12, 3.5e-12, n_delays)
    weights = rng.normal(0, 1.0, n_delays)

    # compute features: binned spike train + reservoir readout at key times
    readout_times = np.array([0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]) * 1e-12
    readout_idx = np.array([np.argmin(np.abs(t - rt)) for rt in readout_times])
    n_bins = 50
    bin_edges = np.linspace(-2e-12, 8e-12, n_bins + 1)

    features = []
    for spikes in X:
        states = reservoir_states(spikes, delay_values, weights, dt)
        # bin the raw spike train
        binned, _ = np.histogram(t, bins=bin_edges, weights=spikes)
        # reservoir readout at selected times
        reservoir_readout = states[readout_idx, :].flatten()
        feat = np.concatenate([
            binned / (binned.max() + 1e-12),
            reservoir_readout,
            states.max(axis=0),
        ])
        features.append(feat)
    features = np.array(features)

    # train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        features, y, test_size=0.3, random_state=42, stratify=y
    )

    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train, y_train)
    train_acc = clf.score(X_train, y_train)
    test_acc = clf.score(X_test, y_test)

    print("train accuracy: %.3f" % train_acc)
    print("test accuracy:  %.3f" % test_acc)

    # example spike trains and reservoir responses
    fig, axes = plt.subplots(3, 2, figsize=(10, 9))
    for cls in range(3):
        idx = np.where(y == cls)[0][0]
        spikes = X[idx]
        states = reservoir_states(spikes, delay_values, weights, dt)

        ax = axes[cls, 0]
        ax.plot(t * 1e12, spikes / spikes.max())
        ax.set_title("class %d input spike train" % cls)
        ax.set_xlim(-2, 8)
        ax.set_xlabel("time (ps)")
        ax.set_ylabel("norm. amplitude")
        ax.grid(True, alpha=0.3)

        ax = axes[cls, 1]
        im = ax.imshow(states.T, aspect="auto", extent=[t[0]*1e12, t[-1]*1e12, 0, n_delays],
                       cmap="viridis", origin="lower")
        ax.set_title("reservoir state (class %d)" % cls)
        ax.set_xlim(-2, 8)
        ax.set_xlabel("time (ps)")
        ax.set_ylabel("delay tap index")
        fig.colorbar(im, ax=ax)

    fig.tight_layout()
    fig.savefig(os.path.join(OUT, "spike_reservoir_demo.png"), dpi=150)
    print("saved results/spike_reservoir_demo.png", flush=True)

    np.savez(os.path.join(OUT, "spike_reservoir_demo.npz"),
             train_acc=train_acc, test_acc=test_acc,
             delay_values=delay_values, weights=weights)


if __name__ == "__main__":
    main()
